name: Create Npoint Backup
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # At 00:00 on Sunday

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Backup
        run: node npoint-backup/backup.js
      - name: Commit backup
        run: |
          git config --global user.name 'Github Backup Action'
          git config --global user.email 'github_backup_action@users.noreply.github.com'
          git add .
          git commit -am "Created Backup $(date +%m_%d_%Y)" && git push || echo nocommit
